### ISSUE TITLE
Reference abbreviation is incorrect in the menu bar

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/PBDB-Wing#36]
In the menu bar, when you have a reference with multiple authors, it should say Smith et al., 1999 NOT Smith etc., 1999. 

![menu bar](https://cloud.githubusercontent.com/assets/19557452/24024609/27a0d9b2-0a8b-11e7-986e-705772d67227.jpeg)

**Comment by jpjenk** [comment]
Corrected. Menu ref citation is now correctly truncated to "et al." if more than two authors.
